version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "50051:50051"
    networks:
      - microservices-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "50052:50051"
    depends_on:
      - user-service
    networks:
      - microservices-network
    environment:
      - USER_SERVICE_ADDR=user-service:50051

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "50053:50051"
    depends_on:
      - order-service
    networks:
      - microservices-network
    environment:
      - ORDER_SERVICE_ADDR=order-service:50051

  review-service:
    build:
      context: .
      dockerfile: review-service/Dockerfile
    container_name: review-service
    ports:
      - "50054:50051"
    depends_on:
      - user-service
      - order-service
    networks:
      - microservices-network
    environment:
      - USER_SERVICE_ADDR=user-service:50051
      - ORDER_SERVICE_ADDR=order-service:50051

networks:
  microservices-network:
    driver: bridge

